# Generated by Django 3.1.1 on 2020-10-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=20)),
                ('resolve_status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
        migrations.CreateModel(
            name='otp_authentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('otp', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=10)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_authentication',
            },
        ),
        migrations.CreateModel(
            name='sah_admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sah_admin',
            },
        ),
        migrations.CreateModel(
            name='sah_area_manager',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('email_verification', models.CharField(max_length=10, null=True)),
                ('upi', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sah_area_manager',
            },
        ),
        migrations.CreateModel(
            name='sah_service_provider',
            fields=[
                ('service_provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('shopname', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/master')),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('salontype', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('verification_status', models.CharField(max_length=50)),
                ('available_status', models.CharField(default='active', max_length=10)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('float_rating', models.FloatField(blank=True, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('manager_commision', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sah_User.sah_area_manager')),
            ],
            options={
                'db_table': 'sah_service_provider',
            },
        ),
        migrations.CreateModel(
            name='sah_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=50)),
                ('wallet_id', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=50)),
                ('email_verification', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sah_user',
            },
        ),
        migrations.CreateModel(
            name='schedular_flag',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('d', models.IntegerField(blank=True, null=True)),
                ('m', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'schedular_flag',
            },
        ),
        migrations.CreateModel(
            name='state_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'state_list',
            },
        ),
        migrations.CreateModel(
            name='user_wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False)),
                ('wallet_cash', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Sah_User.sah_user')),
            ],
            options={
                'db_table': 'user_wallet',
            },
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('txnid', models.CharField(max_length=50)),
                ('amount_sah', models.IntegerField()),
                ('amount_service', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('manager_id', models.IntegerField()),
                ('order_data', models.TextField()),
                ('order_rating', models.IntegerField(blank=True, null=True)),
                ('payment_status', models.CharField(max_length=10)),
                ('addedon', models.DateTimeField(null=True)),
                ('bank_ref_num', models.TextField(null=True)),
                ('order_status', models.CharField(max_length=10)),
                ('notify_mannager', models.CharField(max_length=10, null=True)),
                ('notify_master', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Sah_User.sah_service_provider')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_of_service', models.CharField(max_length=80)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('information', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='images/master/service')),
                ('service_status', models.CharField(default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sah_User.sah_service_provider')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='district_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('state_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='Sah_User.state_list')),
            ],
            options={
                'db_table': 'district_list',
            },
        ),
        migrations.CreateModel(
            name='cartlist',
            fields=[
                ('temp_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('service_provider_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sah_User.service')),
            ],
            options={
                'db_table': 'cartlist',
            },
        ),
    ]
