# Generated by Django 3.1.1 on 2020-11-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sah_User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sah_service_provider',
            name='pincode',
        ),
        migrations.AddField(
            model_name='sah_service_provider',
            name='Pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
